apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    env: dev
	app: flask
  name: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: nishgupta29/vmfarms:latest
        name: vmfarms
      
